### ISSUE TITLE
Response status 403 with description 'Forbidden (no credentials)'

### ISSUE THREAD

**Issue by kruasann** [guinmoon/alice_suno#1]
При попытке воспроизвести песню появляется ошибка:

Response status 403 with description 'Forbidden (no credentials)'
Oops! Error uploading sound by bytes Forbidden (no credentials)

Хотя приведенный OAuth токен и SKILL_Id верные

**Comment by guinmoon** [comment]
Эта ошибка возникает в плагине Node-Red?

**Comment by kruasann** [comment]
Нет, это происходит в alice_suno.py

**Comment by guinmoon** [comment]
Получите токен по [этой](https://yandex.ru/dev/dialogs/alice/doc/resource-sounds-upload.html) инструкции, раздел "Загрузка аудиофайла через HTTP API"

**Comment by guinmoon** [comment]
Возможно вы указываете токен который подходит для node-red но не подходит для загрузки аудиофайла

**Comment by guinmoon** [comment]
Токен нужно указывать в формате "OAuth <ваш токен>"

**Comment by kruasann** [comment]
Да, все помогло
